### ISSUE TITLE
Copy of code with line numbers includes line numbers

### ISSUE THREAD

**Issue by dimitri-koenig** [tempestphp/highlight#126]
Currently line numbers are included if one wants to copy the code. It would be really nice if those line numbers would be excluded. Take GitHub code display as an example where line numbers are excluded from selecting any code lines.

**Comment by brendt** [comment]
Which theme are you using? The `hl-gutter` class should have the following CSS:

```css
.hl-gutter {
    …
    user-select: none;
}
```
