### ISSUE TITLE
Option for ability to remove blur on hover

### ISSUE THREAD

**Issue by eznix86** [tempestphp/highlight#144]
It would be nice if we had a feature where we can enable and disable blur on hover.

```php
(new Highlighter())->withRemoveBlurOnHover(enabled: true);
```

**Comment by brendt** [comment]
This can be done by extending the theme: 

```css
.hl-blur:hover {
    filter: none;
}
```

I don't think it's worth adding options in the engine for it.
